################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/BayesFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/InterpolationFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/QuaternionMathFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/BasicMathFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/ReshapeFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/SVDFunctions \
Core/Inc/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions \
Core/Inc/edge-impulse-sdk/classifier \
Core/Inc/edge-impulse-sdk/dsp/dct \
Core/Inc/edge-impulse-sdk/dsp/image \
Core/Inc/edge-impulse-sdk/dsp/kissfft \
Core/Inc/edge-impulse-sdk/dsp \
Core/Inc/edge-impulse-sdk/porting/ambiq \
Core/Inc/edge-impulse-sdk/porting/android \
Core/Inc/edge-impulse-sdk/porting/arduino \
Core/Inc/edge-impulse-sdk/porting/brickml \
Core/Inc/edge-impulse-sdk/porting/ceva-npn \
Core/Inc/edge-impulse-sdk/porting/clib \
Core/Inc/edge-impulse-sdk/porting/ethos-core-driver/src \
Core/Inc/edge-impulse-sdk/porting/himax \
Core/Inc/edge-impulse-sdk/porting/himax-we2 \
Core/Inc/edge-impulse-sdk/porting/iar \
Core/Inc/edge-impulse-sdk/porting/infineon-psoc62 \
Core/Inc/edge-impulse-sdk/porting/mbed \
Core/Inc/edge-impulse-sdk/porting/mingw32 \
Core/Inc/edge-impulse-sdk/porting/particle \
Core/Inc/edge-impulse-sdk/porting/posix \
Core/Inc/edge-impulse-sdk/porting/raspberry \
Core/Inc/edge-impulse-sdk/porting/renesas-ra \
Core/Inc/edge-impulse-sdk/porting/seeed-vision-ai \
Core/Inc/edge-impulse-sdk/porting/silabs \
Core/Inc/edge-impulse-sdk/porting/sony \
Core/Inc/edge-impulse-sdk/porting/stm32-cubeai \
Core/Inc/edge-impulse-sdk/porting/synaptics \
Core/Inc/edge-impulse-sdk/porting/ti \
Core/Inc/edge-impulse-sdk/porting/zephyr \
Core/Inc/edge-impulse-sdk/tensorflow/lite/c \
Core/Inc/edge-impulse-sdk/tensorflow/lite/core/api \
Core/Inc/edge-impulse-sdk/tensorflow/lite/kernels/custom \
Core/Inc/edge-impulse-sdk/tensorflow/lite/kernels/internal \
Core/Inc/edge-impulse-sdk/tensorflow/lite/kernels \
Core/Inc/edge-impulse-sdk/tensorflow/lite/micro \
Core/Inc/edge-impulse-sdk/tensorflow/lite/micro/kernels \
Core/Inc/edge-impulse-sdk/tensorflow/lite/micro/memory_planner \
Core/Inc/tflite-model \
Core/Src \
Core/Startup \
Drivers/STM32F0xx_HAL_Driver/Src \

